import { defineStore } from "pinia";
import { CarPart } from "../types/cardType";

export const useProductStore = defineStore("product", () => {
  const cards: CarPart[] = reactive([
    {
      to: "mobili-150866-ulje-za-motor-hemijski-proizvodi",
      image: "/images/prod1.jpg",
      main_category: "Elektrika i Elektronika",
      category: "Akumulatori",
      title: "MOBIL - 150866 - ULJE ZA MOTOR (HEMIJSKI PROIZVODI)",
      oldPrice: 2199,
      newPrice: 1599,
      mark: "BMW",
      model: "X4",
      year: "2005",
      type: "popular",
      discount: 15,
      showFilledHeart: false,
      id: "A1",
    },
    {
      to: "mobili-150236-ulje-za-motor-hemijski-proizvodi",
      image: "/images/prod2.jpg",
      main_category: "Motor i Pogon",
      category: "Motorne komponente",
      title: "MOBIL - 150236 - ULJE ZA MOTOR (HEMIJSKI PROIZVODI)",
      oldPrice: 2199,
      newPrice: 1599,
      mark: "Audi",
      model: "Q7",
      year: "2008",
      type: "popular",
      discount: 0,
      showFilledHeart: false,
      id: "B1",
    },
    {
      to: "mobili-150866-ulje-za-motor-hemijski-proizvodi",
      image: "/images/prod3.jpg",
      main_category: "Motor i Pogon",
      category: "Motorne komponente",
      title: "MOBIL - 150866 - ULJE ZA MOTOR (HEMIJSKI PROIZVODI)",
      oldPrice: 2199,
      newPrice: 1599,
      mark: "BMW",
      model: "X4",
      year: "2005",
      type: "popular",
      discount: 20,
      showFilledHeart: false,
      id: "C1",
    },
    {
      to: "mobili-150866-ulje-za-motor-hemijski-proizvodi",
      image: "/images/prod4.jpg",
      main_category: "Motor i Pogon",
      category: "Filteri za motor",
      title: "MOBIL - 150866 - ULJE ZA MOTOR (HEMIJSKI PROIZVODI)",
      oldPrice: 2199,
      newPrice: 1599,
      mark: "Audi",
      model: "Q7",
      year: "2008",
      type: "popular",
      discount: 0,
      showFilledHeart: false,
      id: "G1",
    },
    {
      to: "mobili-150866-ulje-za-motor-hemijski-proizvodi",
      image: "/images/prod2.jpg",
      main_category: "Elektrika i Elektronika",
      category: "Akumulatori",
      title: "MOBIL - 150866 - ULJE ZA MOTOR (HEMIJSKI PROIZVODI)",
      oldPrice: 2199,
      newPrice: 1599,
      mark: "BMW",
      model: "X4",
      year: "2005",
      type: "feautured",
      discount: 15,
      showFilledHeart: false,
      id: "D1",
    },
    {
      to: "mobili-150866-ulje-za-motor-hemijski-proizvodi",
      image: "/images/prod1.jpg",
      main_category: "Motor i Pogon",
      category: "Filteri za motor",
      title: "MOBIL - 150866 - ULJE ZA MOTOR (HEMIJSKI PROIZVODI)",
      oldPrice: 2199,
      newPrice: 1599,
      mark: "Audi",
      model: "Q7",
      year: "2008",
      type: "new",
      discount: 0,
      showFilledHeart: false,
      id: "G1",
    },
    {
      to: "mobili-150866-ulje-za-motor-hemijski-proizvodi",
      image: "/images/prod4.jpg",
      main_category: "Motor i Pogon",
      category: "Pumpa za gorivo",
      title: "MOBIL - 150866 - ULJE ZA MOTOR (HEMIJSKI PROIZVODI)",
      oldPrice: 2199,
      newPrice: 1599,
      mark: "BMW",
      model: "X4",
      year: "2005",
      type: "new",
      discount: 0,
      showFilledHeart: false,
      id: "E1",
    },
    {
      to: "mobili-150866-ulje-za-motor-hemijski-proizvodi",
      image: "/images/prod3.jpg",
      main_category: "Motor i Pogon",
      category: "Pumpa za gorivo",
      title: "MOBIL - 150866 - ULJE ZA MOTOR (HEMIJSKI PROIZVODI)",
      oldPrice: 0,
      newPrice: 1599,
      mark: "Audi",
      model: "Q7",
      year: "2008",
      type: "feautured",
      discount: 0,
      showFilledHeart: false,
      id: "F1",
    },
  ]);

  return { cards };
});
